### ISSUE TITLE
Features to add

### ISSUE THREAD

**Issue by iP0G** [airforce270/CytubeBot#1]
Features to add:
- $pyramid (2m user cooldown 20s global cooldown)
- $rngkick(mod or higher only)
- $poof (mutes user that uses it for random amount of time 5s-10m) bot says: /me timed out [user] for x
- $rngmute (mutes random user (between 5s-2min))(mod or higher only) bot says: /me timed out [user] for x
- $tmute [username] [time] (timed mute)(mod or higher only)
- $roulette
- $smp
- $p (shows user their points)
- (points added to users in userlist 10points every 10min for non afk/3points every 10 min for afk)
- $givepoints [username] [amount]
- (ability to have points saved between bot restarting and bot updating)
- $gmodules true/false (to turn gamba modules on and off(not including points added over time))(mod or higher only)
- $userstats (ability to have them saved over bot reset/update)
- $spam [amount] [text/emote] (mod or higher only)
- $commands (links a page with user commands(not including moderation commands))
- (change $blockuser perms to mod to be able to use)

**Comment by airforce270** [comment]
Pretty large-scope issue, going to split into smaller ones

**Comment by airforce270** [comment]
Split into sub-issues, closing
