### ISSUE TITLE
$slowmode on/off

### ISSUE THREAD

**Issue by Xsogon** [airforce270/CytubeBot#100]
$slowmode on
bot changes chat throttle for slow mode

could also change 'Max total queue time per user' and 'Max video length'
(good for offline jams)

$slowmode off could revert it back to normal

**Comment by iP0G** [comment]
ADDED

$slowmode on sets chat_antiflood: true, maxlength: 600, new_user_chat_link_delay: 900, playlist_max_duration_per_user: 1800

$slowmode off sets chat_antiflood: false, maxlength: 3600, new_user_chat_link_delay: 600, playlist_max_duration_per_user: 7200

$slowmode reg sets chat_antiflood: true, maxlength: 3600, new_user_chat_link_delay: 600, playlist_max_duration_per_user: 7200
