### ISSUE TITLE
Troll skipping mods notification

### ISSUE THREAD

**Issue by airforce270** [airforce270/CytubeBot#67]
DM the ![](https://cdn.betterttv.net/emote/5ec068a99af1ea16863b2fc7/2x) if user skips 3 songs in a row

**Comment by airforce270** [comment]
the events emitted by the server don't include which user voteskipped so likely not possible

**Comment by Xsogon** [comment]
when people skip it says 'Meh.. ResidentSleeper'

have the bot look for that

**Comment by airforce270** [comment]
If a user doesn't have scripts enabled it won't send "Meh.." though
