### ISSUE TITLE
Points / gamba system

### ISSUE THREAD

**Issue by airforce270** [airforce270/CytubeBot#8]
From #1:

- $roulette
- $smp (slot machine pull)
- $p (shows user their points)
- (points added to users in userlist 10points every 10min for non afk/3points every 10 min for afk)
- $givepoints [username] [amount]
- (ability to have points saved between bot restarting and bot updating)
- $gmodules true/false (to turn gamba modules on and off(not including points added over time))(mod or higher only)

**Comment by airforce270** [comment]
@iP0G, what's the difference between $smp and $p? (I don't know the difference between the two in Twitch chat)

Which would be used for roulette?

**Comment by iP0G** [comment]
@airforce270 $p shows the users points
$smp is slot machine pull
